# Tells dbt "Hey, our raw data is in the RAW schema with these 4 tables"
sources: 
  - name: raw
    database: ANALYTICS_DB
    schema: RAW 
    tables:
      - name : OLIST_CUSTOMERS_DATASET
      - name : OLIST_ORDERS_DATASET
      - name : OLIST_ORDER_ITEMS_DATASET
      - name : OLIST_PRODUCTS_DATASET